[package]
name = "tsdistances_gpu"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.3.1"
dashmap = "6.1.0"
krnl = {git="https://github.com/albertoazzari/krnl.git"}
lazy_static = "1.5.0"
rand = "0.8.5"
rustfft = "6.2.0"
vulkano = {git="https://github.com/albertoazzari/vulkano.git"}
